### ISSUE TITLE
Test failure for `UpdateViewModel`

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#485]
### Describe the issue
One of our CI builds hit a failure in a test case for the app update UI.

This could be a flaky test or it could be an issue due to Google Play unblocking our internal store listing.

### Actual behavior + errors
```
validate_result_of_update_methods_calls in co.electriccoin.zcash.ui.screen.update.integration.UpdateViewModelTest
java.lang.AssertionError: actual value is not null expected null, but was:<com.google.android.play.core.appupdate.AppUpdateInfo@77a4366>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotNull(Assert.java:756)
at org.junit.Assert.assertNull(Assert.java:738)
at kotlin.test.junit.JUnitAsserter.assertNull(JUnitSupport.kt:52)
at kotlin.test.AssertionsKt__AssertionsKt.assertNull(Assertions.kt:160)
at kotlin.test.AssertionsKt.assertNull(Unknown Source:1)
at kotlin.test.AssertionsKt__AssertionsKt.assertNull$default(Assertions.kt:159)
at kotlin.test.AssertionsKt.assertNull$default(Unknown Source:1)
at co.electriccoin.zcash.ui.screen.update.integration.UpdateViewModelTest$validate_result_of_update_methods_calls$1$invokeSuspend$$inlined$collectIndexed$1.emit(Collect.kt:127)
at kotlinx.coroutines.flow.FlowKt__LimitKt$take$2$1.emit(Limit.kt:61)
at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
at kotlinx.coroutines.flow.FlowKt__LimitKt$take$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:115)
at co.electriccoin.zcash.ui.screen.update.integration.UpdateViewModelTest$validate_result_of_update_methods_calls$1.invokeSuspend(UpdateViewModelTest.kt:109)
at co.electriccoin.zcash.ui.screen.update.integration.UpdateViewModelTest$validate_result_of_update_methods_calls$1.invoke(Unknown Source:8)
at co.electriccoin.zcash.ui.screen.update.integration.UpdateViewModelTest$validate_result_of_update_methods_calls$1.invoke(Unknown Source:4)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invokeSuspend(TestBuilders.kt:208)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke(Unknown Source:8)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke(Unknown Source:4)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:207)
at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source:1)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invokeSuspend(TestBuilders.kt:167)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(Unknown Source:8)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(Unknown Source:2)
at kotlinx.coroutines.test.TestBuildersJvmKt$createTestResult$1.invokeSuspend(TestBuildersJvm.kt:13)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source:1)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source:1)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest$default(TestBuilders.kt:147)
at kotlinx.coroutines.test.TestBuildersKt.runTest$default(Unknown Source:1)
```

**Comment by HonzaR** [comment]
Hi @ccjernigan, I've just checked this test failure. Unfortunately, I couldn't be able to reproduce it on any of these devices: emulators: SDK 27, 31, physical devices Nexus 7 SDK 27, Pixel 4a 5G SDK 32, Huawei SDK 28. So for now I'd just move it back to our backlog and check it later again, or analyze it again once it occurs again. What do you think?

**Comment by HonzaR** [comment]
We're closing this up for now as non-reproducible. We'll open it again, once it appears again.
