### ISSUE TITLE
Fix broken authentication to FTL with flankAuth task

### ISSUE THREAD

**Issue by HonzaR** [zcash/secant-android-wallet#612]
### Describe the issue
Authentication to our cloud-based automation tests service Firebase Test Lab is broken. The flow of using `./gradlew flankAuth` is not working now. 

### Can you reliably reproduce the issue?
Switch to the latest commit on main branch fill in necessary `ZCASH_FIREBASE_TEST_LAB_PROJECT=android-firebase-b0cf1` gradle.properties value and run `./gradlew flankAuth`.

### Expected behavior
A caller is authenticated to FTL and can then do the local running of our tests on the FTL service, as described in https://github.com/zcash/secant-android-wallet/blob/main/docs/Setup.md#firebase-test-lab.

### Actual behavior + errors
Actually the calling of authentication through the flank fails with:
```
> Task :app:flankAuth FAILED
Visit the following URL in your browser:
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&redirect_uri=http://localhost:8085/oauth2callback&scope=https://www.googleapis.com/auth/cloud-platform&access_type=offline&approval_prompt=force&login_hint=flank&include_granted_scopes=true
java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:251)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
The link to the browser seems to be working, as well as the authentication through the browser itself, but the Gradle task is failing independently on the result from the browser.

**Comment by HonzaR** [comment]
Update: the `flankAuth` command seems to be working when run from AS Gradle tasks (still not working form cmd). But the following command `runFlank` fails for me with:
```
Flank encountered a 403 error when running on project android-sdk-14de8. Please verify this credential is authorized for the project and has the required permissions.
Consider authentication with a Service Account https://github.com/Flank/flank#authenticate-with-a-service-account
or with a Google account https://github.com/Flank/flank#authenticate-with-a-google-account

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://toolresults.googleapis.com/toolresults/v1beta3/projects/android-sdk-14de8:initializeSettings
{
  "code": 403,
  "errors": [
    {
      "domain": "global",
      "message": "The caller does not have permission",
      "reason": "forbidden"
    }
  ],
  "message": "The caller does not have permission",
  "status": "PERMISSION_DENIED"
}
```
